start .\TspAgent\bin\Debug\TspAgent.exe Slavic
start .\TspAgent\bin\Debug\TspAgent.exe Kostia
start .\TspAgent\bin\Debug\TspAgent.exe Filip
start .\TspAgent\bin\Debug\TspAgent.exe Vova
start .\TspAgent\bin\Debug\TspAgent.exe Ilia
start .\TspAgent\bin\Debug\TspAgent.exe Maks
start .\TspAgent\bin\Debug\TspAgent.exe Mark
start .\TspAgent\bin\Debug\TspAgent.exe Denis
start .\TspAgent\bin\Debug\TspAgent.exe Sergi
start .\TspAgent\bin\Debug\TspAgent.exe Neli